// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjrfmsfctfxgzueazwjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqcmZtc2ZjdGZ4Z3p1ZWF6d2pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDAwMjgsImV4cCI6MjA2NDExNjAyOH0.9rBOBORHusy4HCAeyF0EeSQ_LNBSWwNTu3wSbLy21bo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});